language: csharp
solution: DiscImageChef.sln
mono:
 - latest
 - 5.2.0
notifications:
  irc:
    channels:
      - "chat.freenode.net#DiscImageChef"
    skip_join: true
    template:
      - "Commit %{commit} by %{author} in %{branch} did %{result} after %{duration}."
      - "Details on %{build_url}, changes on %{compare_url}"