# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
  submodules: true
#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'build'
#    projects: 'DiscImageChef/DiscImageChef.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: 'DiscImageChef/DiscImageChef.csproj'
    publishWebProjects: false
    arguments: '-r linux-x64 -o $(Build.ArtifactStagingDirectory)/out/linux-amd64'
    zipAfterPublish: false
- task: CmdLine@2
  inputs:
    script: 'apt-get -y install p7zip'
    failOnStderr: true
- task: CmdLine@2
  inputs:
    script: '7z a -t7z -bb3 $(Build.ArtifactStagingDirectory)/$(Build.BuildId).7z $(Build.ArtifactStagingDirectory)/out/*'
    failOnStderr: true